repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix"]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v7.32.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
